# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['SmartMetrology_Design_new.py'],
    pathex=['D:\siri\calipers\prometrix\prometrix'],
    binaries=[],
    datas=[(r'D:\siri\calipers\prometrix\prometrix\Smart_Metrology_19082024' , 'Smart_Metrology_19082024'),
    (r'D:\siri\calipers\prometrix\prometrix\Smart_Metrology_19082024' , 'Smart_Metrology_19082024/Tool_Bar'),
    (r'D:\siri\calipers\prometrix\prometrix\UI_Icons', 'UI_Icons'),
    (r'D:\siri\calipers\prometrix\prometrix\algorithms.py', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\api_endpoints.py', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\dialogs.py', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\events.py', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\graphics.py', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\ultralytics', 'ultralytics'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\torch', 'torch'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\torchvision', 'torchvision'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\pyparsing', 'pyparsing'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\cycler', 'cycler'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\kiwisolver', 'kiwisolver'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\tqdm', 'tqdm'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\tqdm-*.dist-info', 'tqdm-4.67.1.dist-info'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\torchvision-*.dist-info', 'torchvision-2.6.0.dist-info'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\sympy', 'sympy'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\mpmath', 'mpmath'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\dotenv', 'dotenv'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\bleak', 'bleak'),
    (r'D:\siri\calipers\prometrix\prometrix\.env', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\async_timeout', 'async_timeout'),

    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\ultralytics\models', 'ultralytics/models'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\torchvision', 'torchvision'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\torchgen', 'torchgen'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\matplotlib', 'matplotlib'),
    (r'D:\siri\calipers\prometrix\prometrix\highlight_manager.py', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\venv\Lib\site-packages\ultralytics\cfg\default.yaml', 'ultralytics/cfg'),
    (r'D:\siri\calipers\prometrix\prometrix\best.pt', '.'),
    (r'D:\siri\calipers\prometrix\prometrix\ui_smart_metrology.py', '.')],
    hiddenimports=[
           'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtWidgets', 'PyQt5.QtGui',
    'PyQt5.sip',
    'qasync', 'bleak', 'asyncio',
    'torch',
    'torch.nn',
     'pyparsing',
    'packaging',
     'tqdm',
     'mpmath',
     'dotenv',
     'bleak',
'packaging.version',
'pyparsing',
'pyparsing.results',
'pyparsing.util',
'pyparsing.common',
'pyparsing.core',
'pyparsing.diagram',
'pyparsing.exceptions',
'pyparsing.helpers',
'pyparsing.unicode',
'pyparsing.testing',
'async_timeout',
 'cycler',
  'dateutil',
    'dateutil.parser',
    'dateutil.tz',
    'torchgen',
    'torch.nn.functional',
    'kiwisolver',
    'torch.utils',
     'timeit',
    'math',
     'matplotlib.backends.backend_tkagg',  # <- required for some matplotlib backends
    'matplotlib.pyplot',
    'matplotlib',
    'unittest.mock',
    'pickletools',
    'numbers',
    'collections.abc',
    'logging.config',
    'PIL.Image', 'PIL.ImageDraw', 'PIL.ImageFont',
    'threading',
    'concurrent.futures',
    'sympy',
    'torch.utils.data',
    'torchvision',
    'torchvision.transforms',
    'torchvision.models',
     'ultralytics', 'ultralytics.nn', 'ultralytics.utils', 'ultralytics.yolo.engine.model',
    'numpy.linalg._umath_linalg',
    'numpy.core._multiarray_umath',
    'numpy.libs'  ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SmartMetrology_Design_new',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SmartMetrology_Design_new',
)
